stages:
  - validate
  - conformance
  - build

validate:
  stage: validate
  image:
    name: garethr/kubeval
    entrypoint:
      - ""
  script:
    - kubeval --strict deploy/*

conformance:
  stage: conformance
  image:
    name: instrumenta/conftest:latest
    entrypoint:
      - ""
  script:
    - conftest test deploy/*